### ISSUE TITLE
shen-js on Node fails after install

### ISSUE THREAD

**Issue by optevo** [gravicappa/shen-js#11]
shen installs with no errors but when I try to execute I get:

shen-js-node@0.10.1 /usr/local/lib/node_modules/shen-js-node
└── commander@1.1.1 (keypress@0.1.0)
shen-js-master$ shen-js
/usr/local/lib/node_modules/shen-js-node/shen.js:1053
    this.io = opts.io(this);
                   ^
TypeError: object is not a function
    at Shen.init (/usr/local/lib/node_modules/shen-js-node/shen.js:1053:20)
    at Object.setup (/usr/local/lib/node_modules/shen-js-node/runtime-node/lib.js:77:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/shen-js-node/shen-node.js:8:42)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
shen-js-master$ node -v
v0.12.5
shen-js-master$

**Comment by gravicappa** [comment]
Node support is outdated (I'm sure that I've written it in README). I
heard that someone started fixing it. Probably I'll try to learn Node
and do it myself. It won't happen «tomorrow» though.

**Comment by optevo** [comment]
You might want to make a note on here too:
https://github.com/gravicappa/shen-js/blob/master/doc/node.md

**Comment by gravicappa** [comment]
Looks like I lied: I've reimplemented Node support.
