### ISSUE TITLE
node -c seems to hang and do nothing

### ISSUE THREAD

**Issue by Gozala** [gravicappa/shen-js#13]
Hi,

I am trying to get my head around what does shen-js can do and what does compiler actually output. When I attempt to compiler simple .shen file as described here https://github.com/gravicappa/shen-js/blob/master/doc/node.md compiler generates empty .js file and never seems to exit finish.

**Comment by Gozala** [comment]
I am also noticing strange error when just loading the file as well:

```
./shen-node.js  examples/factorial.shen
factorial
factorial-tail'
factorial-tail
1307674368000

run time: 0 secs
/Users/gozala/Projects/shen-js/shen-node.js:135
        load_files(files, i + 1, callback);
        ^

ReferenceError: load_files is not defined
    at Shen.receive (/Users/gozala/Projects/shen-js/shen-node.js:135:9)
    at Shen.step (/Users/gozala/Projects/shen-js/shen.js:320:14)
    at Timeout._onTimeout (/Users/gozala/Projects/shen-js/shen.js:326:36)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

although it does seem that code is loaded and executed.

**Comment by gravicappa** [comment]
I'll investigate.

**Comment by Gozala** [comment]
Any updates ?

**Comment by gravicappa** [comment]
Not having much time lately. Tried once got confused more then given up. Today looked once again and fixed that hang.
